### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by meeber**
See [Draft Release](https://github.com/chaijs/chai-jquery/releases/tag/untagged-f3a182d00420c19a3069)

### CODE REVIEW

**Comment by revelt** [comment]
the draft release link on the topmost message above is down

**Comment by meeber** [comment]
@revelt Looks like the draft release notes are only visible to users with write access to the repo.

@keithamus Do you have a min to look at this? Will need help releasing to npm after it's merged too.

**Comment by keithamus** [comment]
Okay looks like a manual publish. Let's merge it then I can publish it.

**Comment by keithamus** [comment]
Ah. I nor the `chaijs` user has publish rights to the npm package. Only @jfirebaugh and @domenic do. 

@jfirebaugh or @domenic could you please go to https://www.npmjs.com/package/chai-jquery/access and add the user `chaijs` as a maintainer with write access!

**Comment by jfirebaugh** [comment]
@keithamus Done!

**Comment by meeber** [comment]
@keithamus Are you able to publish it now? :D

**Comment by keithamus** [comment]
Sorry had some issues with publishing, had to reach out to npm to fix them. All published now 🎉

**Pull request merged**
