### PR TITLE
Improve failure messages

### PR DESCRIPTION
**Pull request by gurdiga**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
So, first commit seems good, though it could arguably be even better, e.g. instead of:

```
expected '#email' to have value 'email@test.com', but the value was undefined
```

a better error would be:

```
expected '#email' to have value 'email@test.com', but nothing matched that selector
```

I don't understand the second commit. I thought you already discovered (https://github.com/chaijs/chai-jquery/pull/58#issuecomment-75784908) that `Uncaught AssertionError: expected { Object (0, 1, ...) } not to be visible` was an error you were getting because you passed the wrong value to `expect`?

The error message I expect from this assertion is something like `expected <div id="section">...</div> not to be visible`, and I think there's something to be said for including the HTML of the actual matched element.

**Comment by gurdiga** [comment]
@jfirebaugh Thank you for looking at this.

Regarding the first commit: I agree that “nothing matched that selector” would be more descriptive, but it seems that part of the message depends on the particular assertion method. 

Regarding the second commit there are two points:

1. The confusion around #58, was because seeing `expected { Object (0, 1, ...) } not to be visible` I (prematurely) concluded that I may have passed the wrong thing to `expect`. I was transitioning from asserts on results of `querySelectorAll` to jquery-chai, and I had both things at some point, so I thought I incorrectly passed it a [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList).

  It turns out, the `{ Object (0, 1, ...) }` part in the failure message came out because of low `chai.config.truncateThreshold`, the value was actually an OK jQuery result.

2. > The error message I expect from this assertion is something like `expected <div id="section">...</div> not to be visible`, and I think there's something to be said for including the HTML of the actual matched element.

  I see how displaying HTML of the inspected element can be valuable, but it seems that when it’s more than a few tags, displaying all that markup actually hurts the scannability of the failure message.

I understand this subject is far from black and white. :)

**Comment by gurdiga** [comment]
@jfirebaugh So, what do you think?

**Comment by KnightOfShaddai** [comment]
I realise that this PR is a year old, but I just wanted to bump it anyway because I think it would be useful for a project I'm working on.  

I'm trying to make the case to a few senior devs to add chai-jquery to our project's dependencies so we can use it in our integration tests.  One of my arguments is that it produces error messages that are much easier to read and understand.  For example:

```
$('.right-column-header').should.contain('Security Scan Details');
expected { Object (0, length, ...) } to contain 'Security Scan Details'

assert.isTrue($('.right-column-header:contains("Security Scan Details")').length === 1);
expected false to be true
```

Although it is an improvement, having the selector in the error message would make it much better.

**Pull request closed without merging**
